### ISSUE TITLE
BISIP executable (Workplace) and BISIP-master code don't fit the same

### ISSUE THREAD

**Issue by MariusLTU** [clberube/BISIP#4]
I have a .dat file that I want to inverse with BISIP.

When I try to do the inversion with a Pelton Cole-Cole model ( 2 modes) on the BISIP executable, it works fine.
But when I want to do it with the BISIP python shell, it doesn't fit anymore for the exact same model.

Any Idea on how to solve this problem?

**Comment by clberube** [comment]
The BISIP executables have not been updated in several years. It is simply too much trouble keeping up with the Python GUI dependencies and PyInstaller. I recommend using BISIP as a Python package and installing the latest version from this repository with the setup.py script using:
`python setup.py install --force`
